### ISSUE TITLE
 request for help

### ISSUE THREAD

**Issue by mathematicalmichael** [crt0mega/i2c-piix4-aura-dkms#1]
Hi, thanks for putting together this repo. 
I got this installed and re-installed OpenRGB afterwards but was unable to detect any devices when launching the app.
I did add my user to the `adm` group, and I did try running the app as root. Not getting any error messages along the way.

Running Ubuntu 20.04, installed just a few days ago, on ASRock Z490 Phantom Gaming 4, which if I understand correctly, should be compatible?

Any/all help is greatly appreciated. Thank you.

PS new to hardware, apologies if I misunderstood the mobo support. I'm only turning here because applying the patch in OpenRGB didn't work (I'm able to see the new driver(?), but when I launch the app, no Devices are shown.

**Comment by crt0mega** [comment]
Hi!

The piix4 i2c controller can only be found on AM4 boards as far as I understood.

What does `lspci -k` show about your SMBus controller?

**Comment by mathematicalmichael** [comment]
Hmph, I see. Well, thanks, and here's what I've got:

```
00:00.0 Host bridge: Intel Corporation Device 9b43 (rev 05)
	DeviceName: Onboard - Other
	Subsystem: ASRock Incorporation Device 9b43
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor PCIe Controller (x16) (rev 05)
	Kernel driver in use: pcieport
00:12.0 Signal processing controller: Intel Corporation Comet Lake PCH Thermal Controller
	DeviceName: Onboard - Other
	Subsystem: ASRock Incorporation Device 06f9
	Kernel driver in use: intel_pch_thermal
	Kernel modules: intel_pch_thermal
00:14.0 USB controller: Intel Corporation Comet Lake USB 3.1 xHCI Host Controller
	DeviceName: Onboard - Other
	Subsystem: ASRock Incorporation Device 06ed
	Kernel driver in use: xhci_hcd
00:14.2 RAM memory: Intel Corporation Comet Lake PCH Shared SRAM
	DeviceName: Onboard - Other
	Subsystem: ASRock Incorporation Device 06ef
00:16.0 Communication controller: Intel Corporation Comet Lake HECI Controller
	DeviceName: Onboard - Other
	Subsystem: ASRock Incorporation Device 06e0
	Kernel driver in use: mei_me
	Kernel modules: mei_me
00:17.0 SATA controller: Intel Corporation Device 06d2
	DeviceName: Onboard - SATA
	Subsystem: ASRock Incorporation Device 06d2
	Kernel driver in use: ahci
	Kernel modules: ahci
00:1b.0 PCI bridge: Intel Corporation Device 06c3 (rev f0)
	Kernel driver in use: pcieport
00:1d.0 PCI bridge: Intel Corporation Comet Lake PCI Express Root Port #9 (rev f0)
	Kernel driver in use: pcieport
00:1f.0 ISA bridge: Intel Corporation Device 0685
	DeviceName: Onboard - Other
	Subsystem: ASRock Incorporation Device 0685
00:1f.3 Audio device: Intel Corporation Comet Lake PCH cAVS
	DeviceName: Onboard - Sound
	Subsystem: ASRock Incorporation Device 1204
	Kernel driver in use: snd_hda_intel
	Kernel modules: snd_hda_intel, snd_sof_pci
00:1f.4 SMBus: Intel Corporation Comet Lake PCH SMBus Controller
	DeviceName: Onboard - Other
	Subsystem: ASRock Incorporation Device 06a3
	Kernel driver in use: i801_smbus
	Kernel modules: i2c_i801
00:1f.5 Serial bus controller [0c80]: Intel Corporation Comet Lake PCH SPI Controller
	DeviceName: Onboard - Other
	Subsystem: ASRock Incorporation Device 06a4
00:1f.6 Ethernet controller: Intel Corporation Ethernet Connection (11) I219-V
	DeviceName: Onboard - Ethernet
	Subsystem: ASRock Incorporation Ethernet Connection (11) I219-V
	Kernel driver in use: e1000e
	Kernel modules: e1000e
01:00.0 VGA compatible controller: NVIDIA Corporation TU104 [GeForce RTX 2080 SUPER] (rev a1)
	Subsystem: eVga.com. Corp. TU104 [GeForce RTX 2080 SUPER]
	Kernel driver in use: nvidia
	Kernel modules: nvidiafb, nouveau, nvidia_drm, nvidia
01:00.1 Audio device: NVIDIA Corporation TU104 HD Audio Controller (rev a1)
	Subsystem: eVga.com. Corp. TU104 HD Audio Controller
	Kernel driver in use: snd_hda_intel
	Kernel modules: snd_hda_intel
01:00.2 USB controller: NVIDIA Corporation TU104 USB 3.1 Host Controller (rev a1)
	Subsystem: eVga.com. Corp. TU104 USB 3.1 Host Controller
	Kernel driver in use: xhci_hcd
01:00.3 Serial bus controller [0c80]: NVIDIA Corporation TU104 USB Type-C UCSI Controller (rev a1)
	Subsystem: eVga.com. Corp. TU104 USB Type-C UCSI Controller
	Kernel driver in use: nvidia-gpu
	Kernel modules: i2c_nvidia_gpu
02:00.0 Network controller: Intel Corporation Wi-Fi 6 AX200 (rev 1a)
	Subsystem: Intel Corporation Wi-Fi 6 AX200
	Kernel driver in use: iwlwifi
	Kernel modules: iwlwifi
03:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller SM981/PM981/PM983
	Subsystem: Samsung Electronics Co Ltd NVMe SSD Controller SM981/PM981/PM983
	Kernel driver in use: nvme
	Kernel modules: nvme

```

**Comment by mathematicalmichael** [comment]
I doubt that there's _no_ way to control this board's RGB via linux, any direction you could point me in would be appreciated, but I think I've already over-invested in figuring this out lol

**Comment by crt0mega** [comment]
> I doubt that there's no way to control this board's RGB via linux, […]

I like your attitude. I also have no doubt that there's another way, but I guess your princess is in another castle.

> […] any direction you could point me in would be appreciated […]

@CalcProgrammer1's [fork](https://github.com/CalcProgrammer1/openrgb-dkms-drivers) might be more helpful. I'm trying to figure out how to merge his changes into my repo but my Git-fu isn't pretty enough.

**Comment by CalcProgrammer1** [comment]
@mathematicalmichael No one has tried OpenRGB on ASRock Intel boards yet, so you're entering uncharted territory here.

On ASRock's AMD boards, they are using the secondary piix4 bus (same as ASUS) to drive an SMBus RGB controller.  Intel chipsets only have one bus and use the i801 driver.  ASUS Intel boards don't use the chipset SMBus.  Instead, there is an SMBus controller built into the Nuvoton Super-IO chip.  ASUS wired their SMBus RGB controller to this.  Linux does not have a driver for the SMBus controller built into the Nuvoton Super-IO chip, so I wrote one, called i2c-nct6775.  This is part of my kernel patch, though is not provided by this repository.  My fork adds this driver.

I have no clue which bus ASRock is using, or if they're even using Nuvoton Super-IO chips.  It's possible they're just using the i801 adapter, in which case Linux does have a driver:

sudo modprobe i2c-i801

It's possible that ASRock also is using a different SMBus address if they're using this bus.  However, they could be doing the same as ASUS and using the Super-IO's SMBus host controller.  It might be worth installing my fork of this repository and loading both drivers:

sudo modprobe i2c-i801

sudo modprobe i2c-nct6775

and then doing:

sudo i2cdetect -l

**Comment by mathematicalmichael** [comment]
thanks @CalcProgrammer1! I really appreciate your response. I tried and failed to follow your instructions for openrgb just to see if it would magically work anyway. I ended up getting a new mobo (asus rog). Only reason I didn't raise an issue on your project was cuz I couldn't remember my gitlab login. when I run detect, the 6775 entry doesn't show up.
